---
env: "Lift"
policy: "Gaussian"
eval: True
gamma: 0.99
tau: 0.005
lr: 0.0003
alpha: 0.2
automatic_entropy_tuning: False
seed: 123321
batch_size: 256
num_steps: 1000000
hidden_size: 256
updates_per_step: 1
start_steps: 10000
target_update_interval: 1
replay_size: 1000000
max_num_episode: 800
---
env: "Stack"
policy: "Gaussian"
eval: True
gamma: 0.99
tau: 0.005
lr: 0.0003
alpha: 0.2
automatic_entropy_tuning: False
seed: 123321
batch_size: 256
num_steps: 1000000
hidden_size: 256
updates_per_step: 1
start_steps: 10000
target_update_interval: 1
replay_size: 1000000
max_num_episode: 800
---
env: "PickPlaceCan"
policy: "Gaussian"
eval: True
gamma: 0.99
tau: 0.005
lr: 0.0003
alpha: 0.2
automatic_entropy_tuning: False
seed: 123321
batch_size: 256
num_steps: 1000000
hidden_size: 256
updates_per_step: 1
start_steps: 10000
target_update_interval: 1
replay_size: 1000000
max_num_episode: 800
